# docker-compose up --build
version: '2.4'
services:
  codebook_env:
    build:
      # only necessary if rebuilding image
      context: .
      dockerfile: codebook.Dockerfile
      args:
        - JHUB_VER
        - PY_VER
        - DIST
        - REPO_OWNER
        - REPO_NAME
        - WORKFLOW_VERSION
    image: registry.vathes.com/datajoint/codebook-${REPO_NAME}:jhub${JHUB_VER}-py${PY_VER}-${DIST}-${WORKFLOW_VERSION}
