# WORKER_COUNT=1 HOST_UID=$(id -u) docker-compose -f ./docker/docker-compose-notebook.yaml -p neurophotonics_standard up --build -d
# docker-compose -f ./docker/docker-compose-notebook.yaml -p neurophotonics_standard down
# Build this image from neurophotonics level on your local machine
version: '2.4'
services:
  standard_worker:
    build:
      # only necessary if rebuilding image
      context: ../
      dockerfile: ./docker/standard_worker.Dockerfile
      args:
        - mode=djlab
    image: registry.vathes.com/sciops/neurophotonics-notebook:v0.0.1
    env_file: dev.env
    environment:
      - NEW_USER=datajoint
      - NEW_HOME=/home/.anaconda
    user: ${HOST_UID}:anaconda
    volumes:
      - ../setup.py:/home/.anaconda/setup.py
      - ../requirements.txt:/home/.anaconda/requirements.txt
      - ../README.md:/home/.anaconda/README.md
      - ../scripts:/home/.anaconda/scripts
      - ../neurophotonics:/home/.anaconda/neurophotonics
      - ../workdir:/home/.anaconda/workdir
    scale: ${WORKER_COUNT:-1}
    ports:
      - 8888:8888
