# WORKER_COUNT=1 HOST_UID=$(id -u) docker-compose -f ./docker/docker-compose-dev.yaml up -d
# WORKER_COUNT=1 HOST_UID=$(id -u) docker-compose -f ./docker/docker-compose-dev.yaml up --build -d
# docker-compose -f ./docker/docker-compose-dev.yaml down
# Build this image from neurophotonics level on your local machine
version: '2.4'
services:
  standard_worker:
    build:
      # only necessary if rebuilding image
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    image: registry.vathes.com/sciops/neurophotonics:v0.0.1
    env_file: dev.env
    environment:
      - NEW_USER=datajoint
      - DATABASE_PREFIX
      - DISPLAY
    user: ${HOST_UID}:anaconda
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../setup.py:/main/setup.py
      - ../requirements.txt:/main/requirements.txt
      - ../README.md:/main/README.md
      - ../scripts:/main/scripts
      - ../neurophotonics:/main/neurophotonics
      - ../workdir:/main/workdir
      - ../dj_local_conf.json:/main/dj_local_conf.json
    scale: ${WORKER_COUNT:-1}
    command:
      - /bin/bash
      - -c
      - |
        set -e
        #tail -f /dev/null
        echo "Running ingest..."
        python3 workdir/ingest.py
        echo "Running pop_fields..."
        python3 scripts/pop_fields.py
        echo "Running pop_geo..."
        python3 scripts/pop_geo.py
        echo "Running pop_sim..."
        python3 scripts/pop_sim.py
        echo "Running pop_demix..."
        python3 scripts/pop_demix.py
