name: Run EC2 instance

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Launch instance
      run: aws ec2 start-instances --instance-ids ${{ secrets.INSTANCE_ID }}
