name: Run EC2 instance

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: List T3As
      run: aws ec2 describe-instances --filters Name=instance-type,Values=t3a.micro --query "Reservations[].Instances[].InstanceId"
